"""Full demonstration of SATE on one source sentence, from the saved judgements (no cost).

Shows every step for the four translations: the source sentence word by word, its
information items, the aligned English, the exact request each judge received, both
judges' verdicts on every item (sense and source) with their reasons, the additions, and
the scores, computed by the unchanged report.sentence_rows. Nothing in sps_validation/
is changed.

    python -m demo.sentence EPH-S013              # a sentence id (Ephesians or Genesis)
    python -m demo.sentence "EPH 2:8"             # or a verse: every sentence of that verse
    python -m demo.sentence JHN-S001 --john       # John 1 (after john.run)

Output: build/demo/<id>.md. It contains the SPS text: keep it private.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from sps_validation import judge as J
from sps_validation import report as R

OUTCOME_RO = {"retained": "retained", "partial": "partial", "lost": "lost", "distorted": "DISTORTED",
              "not_in_base": "not in base"}


def load(john: bool, results: Path | None):
    if john:
        from john.prepare import BUILD, load_units

        units, feats = load_units()
        root = BUILD / "judge"
        reqs = J._jsonl(root / "sets/main.jsonl")
    else:
        units, feats = J.load_sources()
        root = Path("build/judge")
        reqs = J._jsonl(root / "sets/main.jsonl")
    res = R.load_results(results or root / "results", "main")
    if not res:
        raise SystemExit(f"no judge results in {results or root / 'results'}")
    return units, feats, reqs, res


def pick(target: str, units: dict) -> list[str]:
    if target in units:
        return [target]
    ids = [u for u, x in units.items() if target in x["refs"]]
    if not ids:
        raise SystemExit(f"{target}: no such sentence id or verse (e.g. EPH-S013 or \"EPH 2:8\")")
    return ids


def cell(x) -> str:
    """Table-safe text: a | inside a cell would split it."""
    return str(x).replace("|", "·")


def verdict(o: dict | None, key: str) -> str:
    if not o or key not in o:
        return "—"
    return OUTCOME_RO.get(o[key], o[key]) + (" (translit.)" if o.get("transliterated") else "")


def sentence(uid: str, units, feats, reqs, res) -> list[str]:
    u, fl = units[uid], feats[uid]
    toks = {t["id"]: t for t in u["tokens"]}
    L = [f"# {uid} — {', '.join(u['refs'])}", "", f"**Source:** {u['text']}", "",
         "## 1. The source, word by word (MACULA)", "",
         "| Word | Lemma | Parsing |", "|---|---|---|"]
    for t in u["tokens"]:
        if t.get("text"):
            parse = ", ".join(f"{k}={t[k]}" for k in J.TOKEN_FIELDS if t.get(k))
            L.append(f"| {t['text']} | {t.get('lemma', '')} | {parse} |")
    L += ["", f"## 2. The information items ({len(fl)}), generated by features.unit_features", "",
          "| # | Word | Class | What the source encodes |", "|---|---|---|---|"]
    for f in fl:
        L.append(f"| {f['fid'].split('/')[-1]} | {toks.get(f['token'], {}).get('text', '')} | {f['class']} | {cell(f['value'])} |")
    L += ["", "Classes: LEX sense · ASP aspect/tense · STEM Hebrew stem · VOICE · MOOD · REF who is meant · "
              "NUM number · DEF article · REL relation · NEG negation · ARG who does what to whom.", ""]

    mine = [r for r in reqs if uid in r["units"]]
    L += ["## 3. What each translation says here (aligned without verse numbers)", ""]
    for r in mine:
        others = [x for x in r["units"] if x != uid]
        L.append(f"- **{r['translation']}**: {r['english']}" + (f"  _(one group with {', '.join(others)})_" if others else "")
                 + (f"  _(base: {r['edition']})_" if r["edition"] else ""))
    L.append("")

    L += ["## 4. The verdicts of the two judges, item by item", "",
          "Each item gets two independent verdicts: **sense** (does an ordinary reader get this information?) "
          "and **source** (can the source item be recovered from the text?).", ""]
    for r in mine:
        per = {j: R.feature_outcomes(res[j][r["id"]]) for j in res if r["id"] in res[j]}
        L += [f"### {r['translation']} — “{r['english']}”", "",
              "| # | Item | " + " | ".join(f"{j} sense | {j} source" for j in per) + " | English words | Reason |",
              "|---|---|" + "---|---|" * len(per) + "---|---|"]
        for f in fl:
            os_ = {j: p.get(f["fid"]) for j, p in per.items()}
            words = next((o.get("english") for o in os_.values() if o and o.get("english")), "")
            reasons = " / ".join(f"{j}: {o.get('reason', '')}" for j, o in os_.items() if o)
            L.append(f"| {f['fid'].split('/')[-1]} | {toks.get(f['token'], {}).get('text', '')} {f['class']} | "
                     + " | ".join(f"{verdict(o, 'outcome')} | {verdict(o, 'source_outcome')}" for o in os_.values())
                     + f" | {cell(words)} | {cell(reasons)} |")
        adds = {j: res[j][r["id"]]["result"].get("additions", []) for j in per}
        for j, a in adds.items():
            if a:
                L.append("")
                L.append(f"Additions found by {j}: " + "; ".join(f"«{x['english']}» = {x['type']}" for x in a))
        L.append("")

    L += ["## 5. The scores of this sentence (report.sentence_rows, unchanged)", "",
          "Item score: retained 1 · partial 0.5 · lost 0 · distorted 0, averaged over the two judges.",
          "R (retention) = Σ score / items · P (accuracy) = Σ score / (Σ score + distorted + unsupported additions) · "
          "F (fidelity) = 2PR / (P + R).", "",
          "| Translation | Dimension | Items | Σ score | Retained | Partial | Lost | Distorted | Unsupported add. | R | P | F |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for t in J.TRANSLATIONS:
        for d, key in R.DIMENSIONS.items():
            rows = [x for x in R.sentence_rows(mine, res, units, feats, key) if x["sentence"] == uid and x["translation"] == t]
            for x in rows:
                L.append(f"| {t} | {R.DIM_LABEL[d]} | {x['features']} | {x['sum_score']} | {x['retained']} | {x['partial']} | "
                         f"{x['lost']} | {x['distorted']} | {x['unsupported_additions']} | {x['retention']} | "
                         f"{x['accuracy']} | {x['fidelity']} |")
    if mine:
        r = next(x for x in mine if x["translation"] == "WEB") if any(x["translation"] == "WEB" for x in mine) else mine[0]
        L += ["", "## 6. Exactly what a judge received (the WEB request; the others differ only in ENGLISH)", "",
              "The translation's name is never shown: the request id is opaque.", "", "```", r["prompt"], "```", ""]
    return L


def main(argv: list[str]) -> None:
    args = [a for a in argv[1:] if not a.startswith("--")]
    if not args:
        raise SystemExit(__doc__)
    john = "--john" in argv
    results = Path(argv[argv.index("--results") + 1]) if "--results" in argv else None
    if results:
        args = [a for a in args if a != str(results)]
    units, feats, reqs, res = load(john, results)
    lines = []
    for uid in pick(args[0], units):
        lines += sentence(uid, units, feats, reqs, res)
    out = Path("build/demo") / (args[0].replace(" ", "_").replace(":", "_") + ".md")
    out.parent.mkdir(parents=True, exist_ok=True)
    if results and "mock" in str(results):
        lines = ["> **MOCK — random judgements, layout test only. Not results.**", ""] + lines
    out.write_text("\n".join(lines), encoding="utf-8")
    print("written", out.resolve())


if __name__ == "__main__":
    main(sys.argv)
